const fallbackQuotes = [
	"Anger begins with folly, and ends with repentance. ",
	"Nothing good ever comes of violence.",
	"Being In The Present Means Tuning Out Distractions And Paying Attention To What Is Important, Now.",
	"One must be deeply aware of the impermanence of the world.",
	"We all give up great expectations along the way.",
	"Change will not come if we wait for some other person, or if we wait for some other time.",
	"Positive thinking can be contagious. Being surrounded by winners helps you develop into a winner.",
	"Don't let your learning lead to knowledge. Let your learning lead to action.",
	"Courage is not having the strength to go on; it is going on when you don't have the strength.",
	"It's better to stand by someone's side than by yourself.",
	"It takes a great deal of bravery to stand up to our enemies, but just as much to stand up to our friends.",
	"Every great change is preceded by chaos.",
	"The greatest deception men suffer is from their own opinions.",
	"Death smiles at us all. All we can do is smile back.",
	"A clear conscience is the sure sign of a bad memory.",
	"The difference between treason and patriotism is only a matter of dates.",
	"Listen to the secret sound, the real sound, which is inside you.",
	"We are willing to believe anything other than the truth.",
	"Every day may not be good, but there's something good in every day.",
	"No one ever said life was fair. Just Eventful.",
	"I am thankful to all who said no to me. It is because of them that I'm doing it myself.",
	"The older you get the stronger the wind gets - and it's always in your face.",
	"Not everything that weighs you down is yours to carry.",
	"Let not your mind run on what you lack as much as on what you have already.",
	"Patience is a bitter plant, but its fruit is sweet.",
	"All religions, arts and sciences are branches of the same tree. ",
	"Our truest life is when we are in dreams awake.",
	"No problem can be solved from the same level of consciousness that created it.",
	"Where your talents and the needs of the world cross, there lies your vocation.",
	"When the fish is caught we pay no more attention to the trap.",
	"Happiness is not something ready made. It comes from your own actions.",
	"So we beat on, boats against the current, borne back ceaselessly into the past.",
	"You can never get enough of what you don't need to make you happy.",
	"Would you rather live your life according to the approval of others or aligned with your truth and your dreams?",
	"To live outside the law, you must be honest. ",
	"The happiness of your life depends upon the quality of your thoughts; therefore guard accordingly.",
	"Be courteous to all, but intimate with few, and let those few be well tried before you give them your confidence. ",
	"Nothing can bring you peace but yourself.",
	"If you can change your mind, you can change your life.",
	"Others can stop you temporarily - you are the only one who can do it permanently.",
	"The way to change others' minds is with affection, and not anger.",
	"Success is about creating value.",
	"To be happy we need something to solve. Happiness is therefore a form of action.",
	"Those who seek the easy way do not seek the true way.",
	"As you think, so shall you become. ",
	"Don't gain the world and lose your soul. Wisdom is better than silver and gold.",
	"Do not ignore your gift. Your gift is the thing you do the absolute best with the least amount of effort.",
	"All happiness depends on courage and work.",
	"You will never do anything in this world without courage. It is the greatest quality of the mind next to honor.",
	"Perfection is not attainable, but if we chase perfection we can catch excellence.",
];

export default fallbackQuotes;
